### ISSUE TITLE
Drawer not hiding obfuscator overlay

### ISSUE THREAD

**Issue by seveves** [tbekolay/preact-mdl-example#1]
This is not a bug but maybe you can improve or at least explain me how I can get this working.

Please have a look at the following line of code:
https://github.com/tbekolay/preact-mdl-example/blob/master/src/main.tsx#L69

With that line only the drawer will be hidden but not the obfuscator (the black semi-transparent overlay). Is there an elegant way to remove "is-visible" from the obfuscator element?

**Comment by tbekolay** [comment]
Hi @seveves, this repo is based on [this JSFiddle](https://jsfiddle.net/developit/weq28uq3/) from the [preact-mdl](https://github.com/developit/preact-mdl) project. If you look at the fiddle, you'll see that even though only the drawer's `is-visible` is removed, the obfuscator also goes away. That behavior happens for me too, is the same not happening for you?

My suspicion (without knowing the full details) is that mdl's JavaScript listens to the drawer's class attribute and spins off some other things when it's changed. Are you including material.min.js in your page?

**Comment by tbekolay** [comment]
Note that in the example in this repo, [this line](https://github.com/tbekolay/preact-mdl-example/blob/master/src/main.tsx#L5) includes material.min.js in the generated webpack bundle.

**Comment by seveves** [comment]
Hm my project is built on your example and I don't find the thing I'm missing. It looks all good to me but maybe you can have a very short look on it :)
https://github.com/seveves/nfliwa

**Comment by seveves** [comment]
Based on [this](http://stackoverflow.com/questions/31536467/how-to-hide-drawer-upon-user-click/34732400#34732400) I've updated my hide method to `    this.base.parentNode.MaterialLayout.toggleDrawer();`. This works fine for me 👍

**Comment by tbekolay** [comment]
Glad you got it working! Would be happy to have a PR making this change if it's necessary for recent versions of MDL.
