### ISSUE TITLE
Namespace 'preact' has no exported member 'FunctionalComponent'

### ISSUE THREAD

**Issue by sn-aj** [tbekolay/preact-mdl-example#3]
**Issue:** 
webpack: Failed to compile. 

**Command:** 
npm run debug 
npm run build

**Error:** 

ERROR in ~/preact-mdl-example/node_modules/preact-router/index.d.ts
(54,12): error TS2694: Namespace 'preact' has no exported member 'FunctionalComponent'.

ERROR in ~/preact-mdl-example/node_modules/preact-router/index.d.ts
(68,22): error TS2428: All declarations of 'ComponentProps' must have identical type parameters.

ERROR in ~/preact-mdl-example/node_modules/preact-router/index.d.ts
(68,83): error TS2694: Namespace 'preact' has no exported member 'FunctionalComponent'.

ERROR in ~/preact-mdl-example/node_modules/preact/dist/preact.d.ts
(2,12): error TS2428: All declarations of 'ComponentProps' must have identical type parameters.

ERROR in ~/preact-mdl-example/node_modules/preact/dist/preact.d.ts
(40,17): error TS2559: Type 'Component<PropsType, StateType>' has no properties in common with type 'ComponentLifecycle<PropsType, StateType>'.

Kindly instruct how could we resolve this issue. Just starting with React, Preact ecosystem. As per availability of the assignee looking into this issue, will assist to resolve it.

Thank you in advance.

**Comment by tbekolay** [comment]
Hi @sn-aj, thanks for the bug report! I've replicated it locally and will look into it shortly. Looks like something with preact or preact-router has changed since I last looked at this repo.

**Comment by tbekolay** [comment]
Took a while, but I did get this fixed in e780eea0f1ef8a.
